version: '3'
services:
  mysql:
    container_name: todo-mysql
    hostname: todo-mysql
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo
      MYSQL_USER: todo
      MYSQL_PASSWORD: todo
    ports:
      - 3309:3306
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_general_ci']
