DROP DATABASE todo;
CREATE DATABASE todo DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE todo;

CREATE TABLE IF NOT EXISTS todo (
  todo_id     VARCHAR(36) NOT NULL,
  todo        VARCHAR(500) NOT NULL,
  created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (todo_id)
);
